[package]
name = "alephBFT"
authors.workspace = true
edition.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aleph-bft = "^0.36"
parity-scale-codec = { workspace = true }
scale-info = {  workspace = true }
